cmake_minimum_required(VERSION 3.22)
project(nico_owned_control LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(control_sum STATIC sum.cpp)
add_executable(control main.cpp)
target_link_libraries(control PRIVATE control_sum)
enable_testing()
add_test(NAME unit COMMAND control unit)
add_test(NAME integration COMMAND control integration)
