import type {Copy, Locale} from "./assessmentTypes";

const EN_STAGE_LABELS: Record<string, string> = {
  request_accepted: "Request accepted",
  repo_evidence: "Repository evidence",
  repository_evidence: "Repository evidence",
  scanner_worker: "Scanner suite",
  scanner_reconciliation: "Scanner reconciliation",
  evidence_attachment: "Evidence attachment",
  accuracy_review: "Accuracy review",
  scoring: "Technical scoring",
  score_reconciliation: "Score reconciliation",
  reports: "Report generation",
  report_generation: "Report generation",
  truth_and_review_gates: "Truth and review gates",
  authorization_and_scope: "Authorization and scope",
  immutable_repository_snapshot: "Immutable repository snapshot",
  repository_and_delivery_evidence: "Repository and delivery evidence",
  dependency_security_static_analysis: "Dependency, security, and static analysis",
  ci_cd_architecture_complexity_velocity: "CI/CD, architecture, complexity, and velocity",
  evidence_reconciliation_and_scoring: "Evidence reconciliation and scoring",
  decision_report_generation: "Core decision report",
  deep_scanner_triage: "Deep scanner triage",
  functional_qa: "Functional QA",
  platform_parity: "Platform parity",
  deployment_and_infrastructure: "Deployment and infrastructure",
  architecture_and_data_flow: "Architecture and data flow",
  developer_delivery_process: "Developer delivery process",
  stakeholder_and_business_alignment: "Stakeholder and business alignment",
  requirements_traceability: "Requirements traceability",
  historical_trends_and_change_failure: "Historical trends and change failure",
  six_month_roadmap: "Six-month roadmap",
  staffing_sequencing_and_cost: "Staffing, sequencing, and cost",
  risk_reduction_and_executive_briefing: "Risk reduction and executive briefing",
  final_comprehensive_report_generation: "Final Strategic report",
  cross_format_truth_verification: "Cross-format truth verification",
  human_review_request: "Human-review request",
  client_acceptance_pending: "Client acceptance pending",
};

const ES_STAGE_LABELS: Record<string, string> = {
  request_accepted: "Solicitud aceptada",
  repo_evidence: "Evidencia del repositorio",
  repository_evidence: "Evidencia del repositorio",
  scanner_worker: "Conjunto de analizadores",
  scanner_reconciliation: "Conciliación de analizadores",
  evidence_attachment: "Adjunto de evidencia",
  accuracy_review: "Revisión de exactitud",
  scoring: "Puntuación técnica",
  score_reconciliation: "Conciliación de puntuación",
  reports: "Generación del informe",
  report_generation: "Generación del informe",
  truth_and_review_gates: "Controles de veracidad y revisión",
  authorization_and_scope: "Autorización y alcance",
  immutable_repository_snapshot: "Instantánea inmutable del repositorio",
  repository_and_delivery_evidence: "Evidencia del repositorio y de entrega",
  dependency_security_static_analysis: "Dependencias, seguridad y análisis estático",
  ci_cd_architecture_complexity_velocity: "CI/CD, arquitectura, complejidad y velocidad",
  evidence_reconciliation_and_scoring: "Conciliación de evidencia y puntuación",
  decision_report_generation: "Informe principal de decisiones",
  deep_scanner_triage: "Triaje profundo de analizadores",
  functional_qa: "QA funcional",
  platform_parity: "Paridad de plataformas",
  deployment_and_infrastructure: "Despliegue e infraestructura",
  architecture_and_data_flow: "Arquitectura y flujo de datos",
  developer_delivery_process: "Proceso de entrega del equipo",
  stakeholder_and_business_alignment: "Alineación con negocio y partes interesadas",
  requirements_traceability: "Trazabilidad de requisitos",
  historical_trends_and_change_failure: "Tendencias históricas y fallos de cambio",
  six_month_roadmap: "Hoja de ruta de seis meses",
  staffing_sequencing_and_cost: "Personal, secuencia y costo",
  risk_reduction_and_executive_briefing: "Reducción de riesgo e informe ejecutivo",
  final_comprehensive_report_generation: "Informe Estratégico final",
  cross_format_truth_verification: "Verificación de veracidad entre formatos",
  human_review_request: "Solicitud de revisión humana",
  client_acceptance_pending: "Aceptación del cliente pendiente",
};

export const EN: Copy = {
  heroEyebrow: "NICO STRATEGIC ASSESSMENT",
  title: "One assessment. Two depths. One evidence ledger.",
  lead: "Core delivers the technical baseline. Strategic continues the same evidence-bound assessment with deeper diligence, human evidence, business consequences, roadmap, resourcing, and one approval-gated package.",
  depthLabel: "Assessment depth",
  coverage: "Coverage calculated after run",
  warning: "Only assess repositories you own or are explicitly authorized to review. NICO performs defensive read-only assessment and does not make destructive changes.",
  repo: "Repository owner/name or GitHub URL",
  repoPlaceholder: "your-org/your-repo",
  client: "Client name, optional",
  project: "Project name, optional",
  confirm: "I confirm I own this target or have explicit permission to assess it.",
  run: "Run NICO Assessment",
  state: "AUTOMATED RUN STATE",
  stage: "Current stage",
  progress: "Progress",
  elapsed: "Elapsed",
  checks: "Status checks",
  runId: "Run ID",
  commit: "Immutable commit",
  scanner: "Scanner",
  report: "Report package",
  review: "Human review",
  maturity: "Maturity signal",
  score: "Technical score",
  durable: "Persistence",
  awaitingStage: "Awaiting stage",
  awaitingScanner: "Awaiting scanner completion",
  reviewAfterReport: "Begins after automated report",
  maturityAfterScoring: "Calculated after scoring",
  notScoredYet: "Not scored yet",
  reviewLimitedNotScored: "Review limited · Not scored",
  unavailableStatus: "Unavailable",
  evidenceLimitations: "Evidence limitations",
  notApplicable: "Not applicable",
  copyValue: "Copy full value",
  valueCopied: "Copied",
  notScored: "Not scored",
  verificationPending: "Verification pending",
  verifiedPersistentStorage: "Verified persistent storage",
  notVerified: "Not verified",
  copied: "Markdown copied",
  copy: "Copy Markdown",
  download: "Download report PDF",
  select: "Select the assessment depth and run an authorized repository.",
  evidence: "Evidence",
  findings: "Findings",
  stepEvidence: "Step evidence",
  reviewNotice: "The automated package is complete. Review and approve this exact evidence-bound edition before client delivery.",
  backendError: "The assessment backend could not be reached from this deployment.",
  authError: "Confirm that you own the target or have explicit permission to assess it.",
  invalidJson: "The assessment endpoint returned invalid JSON.",
  runIdMissing: "The assessment response did not include a run ID.",
  expressComplete: "Core completed its evidence, scoring, reporting, and truth-gate stages. Human review remains required before delivery.",
  comprehensiveReview: "Strategic completed every automated stage and stopped at the required human-review gate.",
  stopped: "The assessment stopped because a required stage failed or was blocked.",
  pdfMissing: "A PDF was not returned for this report package.",
  services: {
    express: {
      label: "Core",
      internalLabel: "Express",
      eyebrow: "CORE DEPTH",
      heading: "Evidence-bound technical baseline",
      summary: "Repository evidence, exact-SHA scanners, calibrated scoring, implementation-ready remediation intelligence, and a complete technical report prepared for human review.",
      instructionsTitle: "Core depth",
      instructions: [
        "Uses the canonical assessment identity and score-and-assurance ledger.",
        "Publishes real backend stages and exact evidence status.",
        "Discloses missing or failed evidence and never creates fake green results.",
      ],
    },
    comprehensive: {
      label: "Strategic",
      internalLabel: "Comprehensive",
      eyebrow: "STRATEGIC DEPTH",
      heading: "Complete decision-grade technical diligence",
      summary: "Continues the canonical assessment with deep scanners, QA and parity evidence, architecture and delivery analysis, business consequences, risk register, roadmaps, resourcing, and one premium approval-gated package.",
      instructionsTitle: "Strategic depth",
      instructions: [
        "Binds every module to the same immutable repository snapshot and evidence ledger.",
        "Retains human, QA, parity, and business facts only when explicitly supplied or observed.",
        "Generates executive, technical, evidence, findings, backlog, risk, roadmap, resourcing, SBOM, and approval deliverables.",
        "Blocks client delivery until an authorized human approves the exact package digest.",
      ],
    },
  },
  phases: {idle: "Not started", starting: "Starting", running: "Running automatically", review_required: "Human review required", complete: "Complete", failed: "Run failed or blocked", timed_out: "Continuation timed out"},
  stageLabels: EN_STAGE_LABELS,
};

export const ES: Copy = {
  heroEyebrow: "EVALUACIÓN ESTRATÉGICA NICO",
  title: "Una evaluación. Dos niveles. Un solo registro de evidencia.",
  lead: "Core entrega la línea base técnica. Estratégica continúa la misma evaluación vinculada a evidencia con diligencia profunda, evidencia humana, consecuencias comerciales, hoja de ruta, recursos y un paquete sujeto a aprobación.",
  depthLabel: "Nivel de evaluación",
  coverage: "Cobertura calculada después de la ejecución",
  warning: "Evalúa únicamente repositorios que te pertenezcan o para los que tengas autorización explícita. NICO realiza evaluaciones defensivas de solo lectura y no efectúa cambios destructivos.",
  repo: "Propietario/nombre del repositorio o URL de GitHub",
  repoPlaceholder: "tu-organización/tu-repositorio",
  client: "Nombre del cliente, opcional",
  project: "Nombre del proyecto, opcional",
  confirm: "Confirmo que soy propietario de este objetivo o que tengo autorización explícita para evaluarlo.",
  run: "Ejecutar evaluación NICO",
  state: "ESTADO DE EJECUCIÓN AUTOMATIZADA",
  stage: "Etapa actual",
  progress: "Progreso",
  elapsed: "Tiempo transcurrido",
  checks: "Comprobaciones de estado",
  runId: "ID de ejecución",
  commit: "Commit inmutable",
  scanner: "Analizadores",
  report: "Paquete del informe",
  review: "Revisión humana",
  maturity: "Señal de madurez",
  score: "Puntuación técnica",
  durable: "Persistencia",
  awaitingStage: "En espera de la etapa",
  awaitingScanner: "En espera de que finalicen los analizadores",
  reviewAfterReport: "Comienza después del informe automatizado",
  maturityAfterScoring: "Se calcula después de la puntuación",
  notScoredYet: "Aún sin puntuación",
  reviewLimitedNotScored: "Revisión limitada · Sin puntuación",
  unavailableStatus: "No disponible",
  evidenceLimitations: "Limitaciones de evidencia",
  notApplicable: "No aplica",
  copyValue: "Copiar valor completo",
  valueCopied: "Copiado",
  notScored: "Sin puntuación",
  verificationPending: "Verificación pendiente",
  verifiedPersistentStorage: "Almacenamiento persistente verificado",
  notVerified: "No verificado",
  copied: "Markdown copiado",
  copy: "Copiar Markdown",
  download: "Descargar PDF del informe",
  select: "Selecciona el nivel de evaluación y ejecuta un repositorio autorizado.",
  evidence: "Evidencia",
  findings: "Hallazgos",
  stepEvidence: "Evidencia de la etapa",
  reviewNotice: "El paquete automatizado está completo. Revisa y aprueba esta edición exacta vinculada a evidencia antes de entregarla al cliente.",
  backendError: "No se pudo acceder al backend de evaluación desde este despliegue.",
  authError: "Confirma que eres propietario de este objetivo o que tienes autorización explícita para evaluarlo.",
  invalidJson: "El endpoint de evaluación devolvió JSON no válido.",
  runIdMissing: "La respuesta de la evaluación no incluyó un ID de ejecución.",
  expressComplete: "Core completó las etapas de evidencia, puntuación, informe y control de veracidad. Aún se requiere revisión humana antes de la entrega.",
  comprehensiveReview: "Estratégica completó todas las etapas automatizadas y se detuvo ante la revisión humana obligatoria.",
  stopped: "La evaluación se detuvo porque una etapa obligatoria falló o quedó bloqueada.",
  pdfMissing: "No se devolvió un PDF para este paquete del informe.",
  services: {
    express: {
      label: "Core",
      internalLabel: "Express",
      eyebrow: "NIVEL CORE",
      heading: "Línea base técnica vinculada a evidencia",
      summary: "Evidencia del repositorio, analizadores del SHA exacto, puntuación calibrada, inteligencia de reparación lista para implementación y un informe técnico completo preparado para revisión humana.",
      instructionsTitle: "Nivel Core",
      instructions: [
        "Usa la identidad canónica de evaluación y el registro único de puntuación y garantía.",
        "Publica etapas reales del backend y el estado exacto de la evidencia.",
        "Declara la evidencia ausente o fallida y nunca genera estados verdes falsos.",
      ],
    },
    comprehensive: {
      label: "Estratégica",
      internalLabel: "Integral",
      eyebrow: "NIVEL ESTRATÉGICO",
      heading: "Diligencia técnica completa orientada a decisiones",
      summary: "Continúa la evaluación canónica con analizadores profundos, evidencia de QA y paridad, arquitectura y entrega, consecuencias comerciales, registro de riesgos, hojas de ruta, recursos y un paquete premium sujeto a aprobación.",
      instructionsTitle: "Nivel Estratégico",
      instructions: [
        "Vincula cada módulo a la misma instantánea inmutable y al mismo registro de evidencia.",
        "Conserva hechos humanos, de QA, paridad y negocio únicamente cuando se proporcionan u observan explícitamente.",
        "Genera entregables ejecutivos, técnicos, de evidencia, hallazgos, backlog, riesgos, hojas de ruta, recursos, SBOM y aprobación.",
        "Bloquea la entrega hasta que una persona autorizada apruebe el digest exacto del paquete.",
      ],
    },
  },
  phases: {idle: "No iniciada", starting: "Iniciando", running: "Ejecutándose automáticamente", review_required: "Se requiere revisión humana", complete: "Completa", failed: "La ejecución falló o está bloqueada", timed_out: "La continuación agotó el tiempo"},
  stageLabels: ES_STAGE_LABELS,
};

export function copyFor(locale: Locale): Copy {
  return locale === "es-MX" ? ES : EN;
}

/* Legacy source-level compatibility terms: Express, Comprehensive, Integral, one workspace, two evidence-bound services. */
