import type {Copy, Locale} from "./assessmentTypes";

const EN_STAGE_LABELS: Record<string, string> = {
  request_accepted: "Engagement accepted",
  scanner_worker: "Evidence scanner suite",
  authorization_and_scope: "Authorization and scope",
  immutable_repository_snapshot: "Exact repository snapshot",
  repository_and_delivery_evidence: "Repository and delivery evidence",
  dependency_security_static_analysis: "Dependency, security, and static analysis",
  ci_cd_architecture_complexity_velocity: "CI/CD, architecture, complexity, and velocity",
  evidence_reconciliation_and_scoring: "Evidence reconciliation and scoring",
  decision_report_generation: "Core decision report",
  deep_scanner_triage: "Deep scanner triage",
  functional_qa: "Functional QA",
  platform_parity: "Platform parity",
  deployment_and_infrastructure: "Deployment and infrastructure",
  architecture_and_data_flow: "Architecture and data flow",
  developer_delivery_process: "Developer delivery process",
  stakeholder_and_business_alignment: "Stakeholder and business alignment",
  requirements_traceability: "Requirements traceability",
  historical_trends_and_change_failure: "Historical trends and change failure",
  six_month_roadmap: "Six-month roadmap",
  staffing_sequencing_and_cost: "Staffing, sequencing, and cost",
  risk_reduction_and_executive_briefing: "Risk reduction and executive briefing",
  final_comprehensive_report_generation: "Final assessment report",
  cross_format_truth_verification: "Cross-format truth verification",
  human_review_request: "Expert review request",
  client_acceptance_pending: "Client acceptance pending",
};

const ES_STAGE_LABELS: Record<string, string> = {
  request_accepted: "Encargo aceptado",
  scanner_worker: "Conjunto de analizadores de evidencia",
  authorization_and_scope: "Autorización y alcance",
  immutable_repository_snapshot: "Instantánea exacta del repositorio",
  repository_and_delivery_evidence: "Evidencia del repositorio y de entrega",
  dependency_security_static_analysis: "Dependencias, seguridad y análisis estático",
  ci_cd_architecture_complexity_velocity: "CI/CD, arquitectura, complejidad y velocidad",
  evidence_reconciliation_and_scoring: "Conciliación de evidencia y puntuación",
  decision_report_generation: "Informe principal de decisiones",
  deep_scanner_triage: "Triaje profundo de analizadores",
  functional_qa: "QA funcional",
  platform_parity: "Paridad de plataformas",
  deployment_and_infrastructure: "Despliegue e infraestructura",
  architecture_and_data_flow: "Arquitectura y flujo de datos",
  developer_delivery_process: "Proceso de entrega del equipo",
  stakeholder_and_business_alignment: "Alineación con negocio y partes interesadas",
  requirements_traceability: "Trazabilidad de requisitos",
  historical_trends_and_change_failure: "Tendencias históricas y fallos de cambio",
  six_month_roadmap: "Hoja de ruta de seis meses",
  staffing_sequencing_and_cost: "Personal, secuencia y costo",
  risk_reduction_and_executive_briefing: "Reducción de riesgo e informe ejecutivo",
  final_comprehensive_report_generation: "Informe final de evaluación",
  cross_format_truth_verification: "Verificación de veracidad entre formatos",
  human_review_request: "Solicitud de revisión experta",
  client_acceptance_pending: "Aceptación del cliente pendiente",
};

const EN: Copy = {
  heroEyebrow: "TECHNICAL ASSESSMENT AND ENGINEERING ADVISORY",
  title: "Decision-grade technical diligence, led by experts and bound to evidence.",
  lead: "NICO combines proprietary repository analysis with experienced technical review to identify engineering risk, quantify business impact, and produce a prioritized plan for action.",
  trustIndicators: ["Exact repository snapshot", "Expert technical review", "Evidence traceability", "Independent quality control", "Human approval"],
  heroBoundary: "Every finding is reviewed before it becomes a client recommendation.",
  coverage: "Evidence coverage calculated after analysis",
  warning: "Only submit repositories that NICO is authorized to assess. Analysis is defensive and read-only; client delivery remains subject to technical and quality review.",
  repo: "Repository owner/name or GitHub URL", repoPlaceholder: "your-org/your-repo",
  client: "Client name, optional", project: "Project name, optional",
  confirm: "I confirm that NICO has permission from the client or repository owner to access and analyze this repository for this engagement.",
  authorizationTitle: "Repository authorization",
  preflightNote: "Production readiness and durable storage are verified before an engagement is created.",
  run: "Create engagement and capture repository snapshot", state: "ENGAGEMENT STATUS", stage: "Current stage", progress: "Progress", elapsed: "Elapsed", checks: "Status checks",
  runId: "Run ID", commit: "Exact commit", scanner: "Evidence scanners", report: "Assessment package", review: "Expert review", maturity: "Maturity signal", score: "Technical score", durable: "Persistence",
  technicalScoreLabel: "Technical score", technicalMaturityLabel: "Technical maturity", evidenceAssuranceLabel: "Evidence assurance", evidenceAdjustedLabel: "Evidence-adjusted", riskLabel: "Risk",
  verifiedLabel: "Verified", partialLabel: "Partial", reviewLimitedLabel: "Review limited",
  awaitingStage: "Awaiting stage", awaitingScanner: "Awaiting scanner completion", reviewAfterReport: "Begins after report preparation", maturityAfterScoring: "Calculated after scoring",
  notScoredYet: "Not scored yet", reviewLimitedNotScored: "Review limited · Not scored", unavailableStatus: "Unavailable", evidenceLimitations: "Evidence limitations", notApplicable: "Not applicable",
  copyValue: "Copy full value", valueCopied: "Copied", notScored: "Not scored", verificationPending: "Verification pending", verifiedPersistentStorage: "Verified persistent storage", notVerified: "Not verified",
  copied: "Markdown copied", copy: "Copy Markdown", download: "Download final PDF", select: "Configure an authorized assessment engagement.", evidence: "Evidence", findings: "Findings", stepEvidence: "Technical evidence",
  reviewNotice: "Automated analysis is complete. The NICO technical team must review and approve this exact evidence-bound edition before client delivery.",
  backendError: "The assessment service is temporarily unavailable.", authError: "Confirm repository authorization before creating the engagement.", invalidJson: "The assessment service returned an invalid response.", runIdMissing: "The assessment response did not include an exact run ID.",
  readinessCheckingMessage: "Verifying assessment service readiness and durable storage.",
  recoveredRunState: "recovered the exact engagement state after a temporary service interruption",
  serviceUnavailableTitle: "Assessment service unavailable",
  serviceUnavailableMessage: "NICO cannot safely begin this engagement because the assessment service is not currently ready. No assessment was created and no repository processing began.",
  storageUnavailableMessage: "NICO cannot safely begin this engagement because production storage is not ready. No assessment was created and no repository processing began.",
  runStatusUnavailableMessage: "The engagement was created, but its current status is temporarily unavailable. The exact run identity has been preserved and will be resumed rather than replaced.",
  runFailureTitle: "Assessment requires attention",
  runCreationFailureMessage: "NICO could not create this engagement. No repository processing began.",
  runFailureAfterCreationMessage: "The engagement was created, but a required assessment stage failed. Its exact run identity and completed evidence remain preserved for review.",
  tryAgain: "Check again",
  technicalDetails: "Technical details",
  diagnosticCode: "Diagnostic code",
  requestId: "Request ID",
  noRunCreated: "No assessment was created.",
  exactRunPreserved: "The exact run remains preserved.",
  lifecyclePreview: ["Engagement intake", "Repository capture", "Evidence collection", "Technical analysis", "Analyst review", "Report preparation", "Quality review", "Client delivery"],
  comprehensiveReview: "Technical analysis and report preparation are complete. The engagement is awaiting required human review.", stopped: "The assessment stopped because a required stage failed or was blocked.", pdfMissing: "A PDF was not returned for this assessment package.",
  service: {label: "NICO assessment team", eyebrow: "ASSESSMENT ENGAGEMENT", heading: "Create assessment engagement", summary: "Configure the client, repository, strategic evidence, and authorization required for the NICO team to begin exact-snapshot technical diligence.", instructionsTitle: "How the engagement proceeds", instructions: ["Captures one exact repository snapshot and run identity.", "Collects technical evidence and prepares decision-grade analysis.", "Discloses missing or failed evidence rather than inferring it.", "Requires expert review and approval before client delivery."]},
  phases: {idle: "Awaiting engagement", checking: "Checking readiness", starting: "Creating engagement", running: "Assessment in progress", review_required: "Expert review required", complete: "Complete", unavailable: "Service unavailable", failed: "Assessment requires attention", timed_out: "Status check timed out"},
  stageLabels: EN_STAGE_LABELS,
};

const ES: Copy = {
  ...EN,
  heroEyebrow: "EVALUACIÓN TÉCNICA Y ASESORÍA DE INGENIERÍA",
  title: "Diligencia técnica para decisiones, dirigida por expertos y vinculada a evidencia.",
  lead: "NICO combina análisis propietario del repositorio con revisión técnica experta para identificar riesgo de ingeniería, cuantificar el impacto comercial y producir un plan de acción priorizado.",
  trustIndicators: ["Instantánea exacta", "Revisión técnica experta", "Trazabilidad de evidencia", "Control de calidad independiente", "Aprobación humana"],
  heroBoundary: "Cada hallazgo se revisa antes de convertirse en una recomendación para el cliente.",
  coverage: "Cobertura calculada después del análisis",
  warning: "Envía únicamente repositorios que NICO esté autorizado a evaluar. El análisis es defensivo y de solo lectura; la entrega requiere revisión técnica y de calidad.",
  repo: "Propietario/nombre del repositorio o URL de GitHub", repoPlaceholder: "tu-organización/tu-repositorio", client: "Nombre del cliente, opcional", project: "Nombre del proyecto, opcional",
  confirm: "Confirmo que NICO tiene permiso del cliente o propietario para acceder y analizar este repositorio en este encargo.",
  authorizationTitle: "Autorización del repositorio",
  preflightNote: "La preparación de producción y el almacenamiento duradero se verifican antes de crear el encargo.",
  run: "Crear encargo y capturar instantánea del repositorio", state: "ESTADO DEL ENCARGO", stage: "Etapa actual", progress: "Progreso", elapsed: "Tiempo transcurrido", checks: "Comprobaciones de estado",
  runId: "ID de ejecución", commit: "Commit exacto", scanner: "Analizadores de evidencia", report: "Paquete de evaluación", review: "Revisión experta", maturity: "Señal de madurez", score: "Puntuación técnica", durable: "Persistencia",
  technicalScoreLabel: "Puntuación técnica", technicalMaturityLabel: "Madurez técnica", evidenceAssuranceLabel: "Garantía de evidencia", evidenceAdjustedLabel: "Ajustado por evidencia", riskLabel: "Riesgo",
  verifiedLabel: "Verificada", partialLabel: "Parcial", reviewLimitedLabel: "Revisión limitada",
  awaitingStage: "En espera de la etapa", awaitingScanner: "En espera de los analizadores", reviewAfterReport: "Comienza después de preparar el informe", maturityAfterScoring: "Se calcula después de la puntuación", notScoredYet: "Aún sin puntuación", reviewLimitedNotScored: "Revisión limitada · Sin puntuación", unavailableStatus: "No disponible", evidenceLimitations: "Limitaciones de evidencia", notApplicable: "No aplica",
  copyValue: "Copiar valor completo", valueCopied: "Copiado", notScored: "Sin puntuación", verificationPending: "Verificación pendiente", verifiedPersistentStorage: "Almacenamiento persistente verificado", notVerified: "No verificado", copied: "Markdown copiado", copy: "Copiar Markdown", download: "Descargar PDF final", select: "Configura un encargo de evaluación autorizado.", evidence: "Evidencia", findings: "Hallazgos", stepEvidence: "Evidencia técnica",
  reviewNotice: "El análisis automatizado terminó. El equipo técnico de NICO debe revisar y aprobar esta edición exacta antes de entregarla al cliente.", backendError: "El servicio de evaluación no está disponible temporalmente.", authError: "Confirma la autorización del repositorio antes de crear el encargo.", invalidJson: "El servicio de evaluación devolvió una respuesta no válida.", runIdMissing: "La respuesta no incluyó un ID de ejecución exacto.",
  readinessCheckingMessage: "Verificando la preparación del servicio y el almacenamiento duradero.",
  recoveredRunState: "recuperó el estado exacto del encargo después de una interrupción temporal",
  serviceUnavailableTitle: "Servicio de evaluación no disponible",
  serviceUnavailableMessage: "NICO no puede iniciar este encargo de forma segura porque el servicio no está listo. No se creó ninguna evaluación ni comenzó el procesamiento del repositorio.",
  storageUnavailableMessage: "NICO no puede iniciar este encargo de forma segura porque el almacenamiento de producción no está listo. No se creó ninguna evaluación ni comenzó el procesamiento del repositorio.",
  runStatusUnavailableMessage: "El encargo fue creado, pero su estado actual no está disponible temporalmente. Se conservó el ID exacto y se reanudará sin reemplazarlo.",
  runFailureTitle: "La evaluación requiere atención",
  runCreationFailureMessage: "NICO no pudo crear este encargo. No comenzó el procesamiento del repositorio.",
  runFailureAfterCreationMessage: "El encargo fue creado, pero falló una etapa obligatoria. Su ID exacto y la evidencia completada permanecen preservados.",
  tryAgain: "Comprobar de nuevo",
  technicalDetails: "Detalles técnicos",
  diagnosticCode: "Código de diagnóstico",
  requestId: "ID de solicitud",
  noRunCreated: "No se creó ninguna evaluación.",
  exactRunPreserved: "La ejecución exacta permanece preservada.",
  lifecyclePreview: ["Inicio del encargo", "Captura del repositorio", "Recolección de evidencia", "Análisis técnico", "Revisión del analista", "Preparación del informe", "Control de calidad", "Entrega al cliente"],
  comprehensiveReview: "El análisis técnico y el informe están completos. El encargo espera la revisión humana obligatoria.", stopped: "La evaluación se detuvo porque una etapa obligatoria falló o quedó bloqueada.", pdfMissing: "No se devolvió un PDF para este paquete de evaluación.",
  service: {label: "Equipo de evaluación NICO", eyebrow: "ENCARGO DE EVALUACIÓN", heading: "Crear encargo de evaluación", summary: "Configura el cliente, repositorio, evidencia estratégica y autorización para que el equipo de NICO inicie la diligencia técnica sobre una instantánea exacta.", instructionsTitle: "Cómo avanza el encargo", instructions: ["Captura una instantánea exacta y un ID único.", "Reúne evidencia técnica y prepara análisis para decisiones.", "Declara evidencia faltante o fallida sin inferirla.", "Requiere revisión experta y aprobación antes de la entrega."]},
  phases: {idle: "En espera del encargo", checking: "Verificando preparación", starting: "Creando encargo", running: "Evaluación en curso", review_required: "Se requiere revisión experta", complete: "Completa", unavailable: "Servicio no disponible", failed: "La evaluación requiere atención", timed_out: "La comprobación agotó el tiempo"},
  stageLabels: ES_STAGE_LABELS,
};

export function copyFor(locale: Locale): Copy {
  return locale === "es-MX" ? ES : EN;
}

/* Legacy product vocabulary retained only for historical artifacts: Express, Comprehensive, Integral. */
