"use client";
import {useEffect,useState} from 'react';import {getJSON,postJSON} from '../lib/api';
function Card({children}:{children:any}){return <div className="card">{children}</div>}
function Button(props:any){return <button className={'btn '+(props.primary?'primary':'')} {...props}>{props.children}</button>}
function Sidebar(){const items=['findings','drift','repairs','verification','memory','reports','policy','audit-log','settings'];return <aside className="sidebar"><div className="brand">NICO</div><div className="tag">Neural Intelligence Cyber Operations</div><nav className="nav"><a href="/">Mission Control</a>{items.map(i=><a key={i} href={`/${i}`}>{i}</a>)}</nav></aside>}
function Shell({children}:{children:any}){return <div className="shell"><Sidebar/><main className="main"><div className="topbar"><div><h1>NICO Command Center</h1><div className="muted">Repair-first local cyber defense</div></div><span className="badge low">Local Safe Mode</span></div>{children}</main></div>}
function Findings({items}:{items:any[]}){return <Card><h2>Findings</h2><table><thead><tr><th>Severity</th><th>Category</th><th>RYE</th><th>Title</th><th>File</th><th>Masked Evidence</th></tr></thead><tbody>{items.slice(0,40).map((f:any)=><tr key={f.id}><td><span className={`badge ${f.severity}`}>{f.severity}</span></td><td>{f.category}</td><td>{f.rye?.score??'-'}</td><td>{f.title}</td><td>{f.affected_file||f.file_path}</td><td>{f.masked_evidence}</td></tr>)}</tbody></table></Card>}
function Repairs({items}:{items:any[]}){return <Card><h2>Repair Queue</h2><table><thead><tr><th>RYE</th><th>Type</th><th>Status</th><th>Issue</th><th>Approval</th></tr></thead><tbody>{items.slice(0,40).map((r:any)=><tr key={r.id}><td>{r.rye_score}</td><td>{r.repair_type}</td><td><span className="badge low">{r.status}</span></td><td>{r.exact_issue}</td><td>{r.approval_requirement}</td></tr>)}</tbody></table></Card>}
export default function Page(){const [data,setData]=useState<any>({findings:[],drift:[],repairs:[],policy:{},verification:{},memory:{},audit:[],availability:[]}); const path=typeof window!=='undefined'?window.location.pathname:'/'; async function load(){const [findings,drift,repairs,policy,verification,memory,audit,availability]=await Promise.all([getJSON('/findings').catch(()=>[]),getJSON('/drift').catch(()=>[]),getJSON('/repairs').catch(()=>[]),getJSON('/policy').catch(()=>({})),getJSON('/verification/latest').catch(()=>({})),getJSON('/memory').catch(()=>({})),getJSON('/audit-log').catch(()=>[]),getJSON('/scanner-availability').catch(()=>[])]);setData({findings,drift,repairs,policy,verification,memory,audit,availability});} useEffect(()=>{load()},[]); const top=data.repairs?.[0]; return <Shell><div className="grid"><Card><div className="muted">Findings</div><div className="metric">{data.findings.length}</div></Card><Card><div className="muted">Drift</div><div className="metric">{data.drift.length}</div></Card><Card><div className="muted">Repairs</div><div className="metric">{data.repairs.length}</div></Card><Card><div className="muted">Autonomy</div><div className="metric">L{data.policy?.autonomy_level??1}</div></Card></div><div className="section"><Button primary onClick={async()=>{await postJSON('/scan/test-lab');load()}}>Run Test Lab Scan</Button> <Button onClick={async()=>{await postJSON('/scan/drift-demo');load()}}>Run Drift Demo</Button> <Button onClick={async()=>{await postJSON('/reports/generate');load()}}>Export Reports</Button></div>{top&&<div className="section"><Card><h2>Top TGRM Repair</h2><p>RYE {top.rye_score}: {top.exact_issue}</p><pre>{top.codex_ready_patch_prompt}</pre></Card></div>}{path.includes('repairs')?<Repairs items={data.repairs}/>:path.includes('verification')?<Card><h2>Verification</h2><pre>{JSON.stringify(data.verification,null,2)}</pre></Card>:path.includes('memory')?<Card><h2>Repair Memory</h2><pre>{JSON.stringify(data.memory,null,2)}</pre></Card>:path.includes('policy')?<Card><h2>Policy / Autonomy</h2><pre>{JSON.stringify(data.policy,null,2)}</pre></Card>:path.includes('audit-log')?<Card><h2>Audit Log</h2><pre>{JSON.stringify(data.audit,null,2)}</pre></Card>:path.includes('settings')?<Card><h2>Scanner Availability</h2><pre>{JSON.stringify(data.availability,null,2)}</pre></Card>:path.includes('reports')?<Card><h2>Reports</h2><p>Use Export Reports to generate owner, developer, reparodynamic, and compliance reports through the API.</p></Card>:<div className="section"><Findings items={data.findings}/><Repairs items={data.repairs}/></div>}</Shell>}
