from __future__ import annotations

from pathlib import Path


PAGE = Path(__file__).resolve().parents[1] / "apps" / "web" / "app" / "page.tsx"


def _source() -> str:
    return PAGE.read_text(encoding="utf-8")


def test_homepage_has_visible_express_and_mid_selector():
    source = _source()

    assert 'type AssessmentType = "express" | "mid"' in source
    assert 'aria-label="Assessment type"' in source
    assert '>Express</button>' in source
    assert '>Mid</button>' in source
    assert 'aria-pressed={assessmentType === "express"}' in source
    assert 'aria-pressed={assessmentType === "mid"}' in source


def test_express_and_mid_share_one_repository_authorization_intake():
    source = _source()

    assert source.count("Repository owner/name or GitHub URL") == 1
    assert source.count("Client name, optional") == 1
    assert source.count("Project name, optional") == 1
    assert source.count("I confirm I own this target or have explicit permission to assess it.") == 1
    assert "runSelectedAssessment" in source
    assert "Run fresh Express assessment" in source
    assert "Run fresh Mid assessment" in source


def test_mid_uses_unified_run_and_status_endpoints_not_legacy_manual_route():
    source = _source()

    assert "${API_URL}/assessment/mid-run" in source
    assert "${API_URL}/assessment/mid-run/${encodeURIComponent(midRunId)}/status" in source
    assert "Check Mid status" in source
    assert "${API_URL}/assessment/mid`" not in source
    assert "qa_evidence" not in source
    assert "parity_notes" not in source
    assert "stakeholder_notes" not in source
    assert "known_risks" not in source


def test_mid_request_preserves_one_run_scope_and_authorization():
    source = _source()

    required_fragments = [
        "repository,",
        "customer_id: workerCustomerId",
        "project_id: workerProjectId",
        "client_name: clientName",
        "project_name: projectName",
        "authorized_by: authorizedBy",
        "authorization_scope: authorizationScope",
        "authorization_confirmed: authorized",
        "run_scanners: true",
        "refresh_full_evidence: true",
        "auto_continue: true",
    ]
    for fragment in required_fragments:
        assert fragment in source


def test_static_accuracy_style_percentages_are_removed():
    source = _source()

    assert "90–95%" not in source
    assert "75–85%" not in source
    assert "55–70%" not in source
    assert "Calculated after each run" in source
    assert "coverage?.calculated" in source
    assert "Coverage calculated after run" in source


def test_generic_report_builder_is_blocked_for_mid_identity_safety():
    source = _source()

    assert 'if (assessmentType === "mid")' in source
    assert "Mid reports must be generated by the dedicated same-run Mid report pipeline" in source
    assert "The generic report builder is disabled for Mid" in source


def test_mid_result_displays_run_snapshot_scanner_and_persistence_identity():
    source = _source()

    assert "Unified Mid run:" in source
    assert "midResult.repository_snapshot?.commit_sha" in source
    assert "midResult.scanner?.status" in source
    assert "midResult.repository_evidence?.status" in source
    assert "express_report_generated: midResult.express_report_generated" in source
    assert "persistence: midResult.persistence" in source
