"""NICO package."""

from nico.hosted_metadata_auth import install_metadata_auth_for_hosted_assessment
from nico.hosted_dependency_normalization import patch_hosted_assessment_dependency_parsing
from nico.hosted_truth_delivery_gate import patch_client_acceptance_gate_for_report_truth
from nico.report_final_qa import patch_polish_express_result_for_final_qa
from nico.report_truth_runtime_patch import patch_final_report_consistency
from nico.report_pdf_display_patch import apply_pdf_display_patch
from nico.express_report_base_v13 import install_express_report_base_v13
from nico.report_intelligence_professional_pdf import install_professional_report_intelligence_pdf
from nico.report_intelligence_final_pdf_binding import install_report_intelligence_final_pdf_binding
from nico.hosted_report_regression_patch import install_hosted_report_regression_patch
from nico.hosted_evidence_execution_patch import install_hosted_evidence_execution_patch
from nico.hosted_scanner_runtime_diagnostics import install_hosted_scanner_runtime_diagnostics_route
from nico.hosted_scanner_execution_path_patch import install_hosted_scanner_execution_path_patch
from nico.hosted_dependency_scanner_execution_patch import install_hosted_dependency_scanner_execution_patch
from nico.hosted_secret_scanner_execution_patch import install_hosted_secret_scanner_execution_patch
from nico.hosted_static_scanner_execution_patch import install_hosted_static_scanner_execution_patch
from nico.scanner_output_truth_patch import install_scanner_output_truth_patch
from nico.scanner_output_truth_compat import install_scanner_output_truth_compat
from nico.hosted_bandit_triage_workflow_patch import install_bandit_triage_workflow_patch
from nico.hosted_complexity_engine_attachment_patch import install_hosted_complexity_engine_attachment_patch
from nico.report_full_detail_export_patch import install_report_full_detail_export_patch
from nico.client_final_review_gate_patch import install_client_final_review_gate_patch
from nico.release_readiness_summary_patch import install_release_readiness_summary_patch
from nico.hosted_release_readiness_diagnostics import install_hosted_release_readiness_diagnostics_route
from nico.assessment_evidence_bundle_patch import install_assessment_evidence_bundle_patch
from nico.production_release_provider_evidence import install_provider_origin_matching
from nico.operational_alert_normalization import install_operational_alert_normalization
from nico.assessment_recovery_execution_patch import install_assessment_recovery_execution_patch
from nico.assessment_recovery_readiness_patch import install_assessment_recovery_readiness_patch
from nico.backup_restore_readiness_patch import install_backup_restore_readiness_patch
from nico.mid_checkpoint_optional_evidence_compat import install_mid_checkpoint_optional_evidence_compat
from nico.scanner_history_truth import install_scanner_history_truth
from nico.full_scanner_recovery_patch import install_full_scanner_recovery
from nico.full_blocked_state_truth_patch import install_full_blocked_state_truth
from nico.progressive_mid_report_patch import install_progressive_mid_report_patch
from nico.mid_report_professional_v3 import install_mid_report_professional_v3
from nico.mid_report_score_integrity import install_mid_report_score_integrity
from nico.mid_report_section_boundary_patch import install_mid_report_section_boundary_patch
from nico.mid_report_truth_disclosure import install_mid_report_truth_disclosure
from nico.report_flowable_safety import install_report_flowable_safety
from nico.report_markup_safety_v2 import install_report_markup_safety_v2
from nico.mid_report_professional_v4 import install_mid_report_professional_v4
from nico.mid_report_professional_v5 import install_mid_report_professional_v5
from nico.mid_report_v5_compat import install_mid_report_v5_compat
from nico.mid_report_v5_hardening import install_mid_report_v5_hardening
from nico.mid_report_professional_v6 import install_mid_report_professional_v6
from nico.progressive_full_report_patch import install_progressive_full_report_patch
from nico.repository_input_normalization_compat import install_repository_input_normalization
from nico.complexity_score_integrity_patch import install_complexity_score_integrity_patch
from nico.complexity_score_integrity_compat import install_complexity_score_integrity_compat
from nico.complexity_score_integrity_install_compat import install_complexity_score_integrity_reentry_compat
from nico.complexity_density_confidence_patch import install_complexity_density_confidence_patch
from nico.complexity_function_measurement_patch import install_complexity_function_measurement_patch
from nico.final_score_reconciliation_patch import install_final_score_reconciliation_patch
from nico.post_polish_score_reconciliation_patch import install_post_polish_score_reconciliation_patch
from nico.express_completion_score_binding import install_express_completion_score_binding
from nico.express_async_contract_metadata import install_express_async_contract_metadata
from nico.express_progress_persistence_patch import install_express_progress_persistence
from nico.hosted_report_intelligence_enrichment import install_hosted_report_intelligence_enrichment
from nico.report_intelligence_accuracy_patch import install_report_intelligence_accuracy_patch
from nico.triage_aware_scanner_finding_truth import install_triage_aware_scanner_finding_truth
from nico.snapshot_scanner_heartbeat_patch import install_snapshot_scanner_heartbeat
from nico.mid_live_progress_patch import install_mid_live_progress
from nico.mid_start_guard import install_mid_start_guard
from nico.mid_status_read_path import install_mid_status_read_path
from nico.mid_stage_truth_patch import install_mid_stage_truth_patch
from nico.report_quality_gate import install_report_quality_gate
from nico.report_quality_gate_compat import install_report_quality_gate_compat
from nico.snapshot_scanner_resilience_patch import install_snapshot_scanner_resilience
from nico.runtime_heartbeat_atomic_patch import install_runtime_heartbeat_atomic_patch
from nico.runtime_storage_truth_patch import install_runtime_storage_truth
from nico.express_status_liveness_patch import install_express_status_liveness_patch
from nico.storage_serialization_safety import install_storage_serialization_safety
from nico.assessment_persistence_truth_patch import install_assessment_persistence_truth
from nico.mid_terminal_truth_patch import install_mid_terminal_truth_patch
from nico.mid_terminal_truth_compat import install_mid_terminal_truth_compat
from nico.mid_quality_issue_display_patch import install_mid_quality_issue_display_patch
from nico.mid_truth_identity_consistency import install_mid_truth_identity_consistency
from nico.mid_truth_identity_transport import install_mid_truth_identity_transport
from nico.mid_approval_truth_freeze import install_mid_approval_truth_freeze

install_storage_serialization_safety()
install_runtime_heartbeat_atomic_patch()
install_runtime_storage_truth()
install_assessment_persistence_truth()
install_express_status_liveness_patch()
install_metadata_auth_for_hosted_assessment()
patch_hosted_assessment_dependency_parsing()
patch_polish_express_result_for_final_qa()
patch_final_report_consistency()
patch_client_acceptance_gate_for_report_truth()
apply_pdf_display_patch()
install_express_report_base_v13()
install_professional_report_intelligence_pdf()
install_hosted_report_regression_patch()
install_hosted_evidence_execution_patch()
install_hosted_scanner_runtime_diagnostics_route()
install_hosted_scanner_execution_path_patch()
install_hosted_dependency_scanner_execution_patch()
install_hosted_secret_scanner_execution_patch()
install_hosted_static_scanner_execution_patch()
install_scanner_output_truth_patch()
install_scanner_output_truth_compat()
install_bandit_triage_workflow_patch()
install_hosted_complexity_engine_attachment_patch()
install_report_full_detail_export_patch()
install_client_final_review_gate_patch()
install_release_readiness_summary_patch()
install_hosted_release_readiness_diagnostics_route()
install_assessment_evidence_bundle_patch()
install_provider_origin_matching()
install_operational_alert_normalization()
install_assessment_recovery_execution_patch()
install_mid_checkpoint_optional_evidence_compat()
install_assessment_recovery_readiness_patch()
install_backup_restore_readiness_patch()
install_scanner_history_truth()
install_triage_aware_scanner_finding_truth()
install_snapshot_scanner_heartbeat()
install_snapshot_scanner_resilience()
install_full_scanner_recovery()
install_full_blocked_state_truth()
install_progressive_mid_report_patch()
install_mid_report_professional_v3()
install_mid_report_score_integrity()
install_mid_report_section_boundary_patch()
install_mid_report_truth_disclosure()
install_report_flowable_safety()
install_report_markup_safety_v2()
install_progressive_full_report_patch()
install_repository_input_normalization()
install_complexity_score_integrity_patch()
install_complexity_score_integrity_compat()
install_complexity_score_integrity_reentry_compat()
install_complexity_density_confidence_patch()
install_complexity_function_measurement_patch()
install_final_score_reconciliation_patch()
install_post_polish_score_reconciliation_patch()
install_express_completion_score_binding()
install_express_async_contract_metadata()
install_express_progress_persistence()
install_mid_live_progress()
install_mid_start_guard()
install_mid_status_read_path()
install_mid_stage_truth_patch()
install_hosted_report_intelligence_enrichment()
install_report_intelligence_accuracy_patch()
install_report_intelligence_final_pdf_binding()
install_report_quality_gate()
install_report_quality_gate_compat()
install_mid_terminal_truth_patch()
install_mid_terminal_truth_compat()
install_mid_quality_issue_display_patch()
install_mid_truth_identity_consistency()
install_mid_truth_identity_transport()
install_mid_approval_truth_freeze()
# Install after all compatibility layers so the full-depth Mid renderer remains active.
install_mid_report_professional_v4()
# Install the compact decision-ready v5 presentation after v4 so it owns final export.
install_mid_report_professional_v5()
# Preserve legacy report contracts after the v5 renderer is active.
install_mid_report_v5_compat()
# Apply deterministic score, evidence, and PDF safety after all Mid presentation layers.
install_mid_report_v5_hardening()
# Install the executive-actionable v6 renderer last so it owns final PDF, Markdown, and HTML export.
install_mid_report_professional_v6()

__version__ = "0.1.0"
