"""NICO package."""

from nico.hosted_metadata_auth import install_metadata_auth_for_hosted_assessment
from nico.hosted_dependency_normalization import patch_hosted_assessment_dependency_parsing
from nico.hosted_truth_delivery_gate import patch_client_acceptance_gate_for_report_truth
from nico.report_final_qa import patch_polish_express_result_for_final_qa
from nico.report_truth_runtime_patch import patch_final_report_consistency
from nico.report_pdf_display_patch import apply_pdf_display_patch
from nico.hosted_report_regression_patch import install_hosted_report_regression_patch
from nico.hosted_evidence_execution_patch import install_hosted_evidence_execution_patch
from nico.hosted_scanner_runtime_diagnostics import install_hosted_scanner_runtime_diagnostics_route
from nico.hosted_scanner_execution_path_patch import install_hosted_scanner_execution_path_patch
from nico.hosted_dependency_scanner_execution_patch import install_hosted_dependency_scanner_execution_patch
from nico.hosted_secret_scanner_execution_patch import install_hosted_secret_scanner_execution_patch
from nico.hosted_static_scanner_execution_patch import install_hosted_static_scanner_execution_patch
from nico.hosted_bandit_triage_workflow_patch import install_bandit_triage_workflow_patch
from nico.hosted_complexity_engine_attachment_patch import install_hosted_complexity_engine_attachment_patch
from nico.report_full_detail_export_patch import install_report_full_detail_export_patch
from nico.client_final_review_gate_patch import install_client_final_review_gate_patch
from nico.release_readiness_summary_patch import install_release_readiness_summary_patch
from nico.hosted_release_readiness_diagnostics import install_hosted_release_readiness_diagnostics_route
from nico.assessment_evidence_bundle_patch import install_assessment_evidence_bundle_patch
from nico.production_release_provider_evidence import install_provider_origin_matching
from nico.operational_alert_normalization import install_operational_alert_normalization
from nico.assessment_recovery_execution_patch import install_assessment_recovery_execution_patch
from nico.assessment_recovery_readiness_patch import install_assessment_recovery_readiness_patch
from nico.backup_restore_readiness_patch import install_backup_restore_readiness_patch
from nico.mid_checkpoint_optional_evidence_compat import install_mid_checkpoint_optional_evidence_compat
from nico.scanner_history_truth import install_scanner_history_truth
from nico.full_scanner_recovery_patch import install_full_scanner_recovery
from nico.full_blocked_state_truth_patch import install_full_blocked_state_truth
from nico.progressive_mid_report_patch import install_progressive_mid_report_patch
from nico.progressive_full_report_patch import install_progressive_full_report_patch
from nico.repository_input_normalization_compat import install_repository_input_normalization
from nico.complexity_score_integrity_patch import install_complexity_score_integrity_patch
from nico.complexity_score_integrity_compat import install_complexity_score_integrity_compat
from nico.complexity_score_integrity_install_compat import install_complexity_score_integrity_reentry_compat
from nico.complexity_density_confidence_patch import install_complexity_density_confidence_patch
from nico.complexity_function_measurement_patch import install_complexity_function_measurement_patch
from nico.final_score_reconciliation_patch import install_final_score_reconciliation_patch
from nico.post_polish_score_reconciliation_patch import install_post_polish_score_reconciliation_patch

install_metadata_auth_for_hosted_assessment()
patch_hosted_assessment_dependency_parsing()
patch_polish_express_result_for_final_qa()
patch_final_report_consistency()
patch_client_acceptance_gate_for_report_truth()
apply_pdf_display_patch()
install_hosted_report_regression_patch()
install_hosted_evidence_execution_patch()
install_hosted_scanner_runtime_diagnostics_route()
install_hosted_scanner_execution_path_patch()
install_hosted_dependency_scanner_execution_patch()
install_hosted_secret_scanner_execution_patch()
install_hosted_static_scanner_execution_patch()
install_bandit_triage_workflow_patch()
install_hosted_complexity_engine_attachment_patch()
install_report_full_detail_export_patch()
install_client_final_review_gate_patch()
install_release_readiness_summary_patch()
install_hosted_release_readiness_diagnostics_route()
install_assessment_evidence_bundle_patch()
install_provider_origin_matching()
install_operational_alert_normalization()
install_assessment_recovery_execution_patch()
install_mid_checkpoint_optional_evidence_compat()
install_assessment_recovery_readiness_patch()
install_backup_restore_readiness_patch()
install_scanner_history_truth()
install_full_scanner_recovery()
install_full_blocked_state_truth()
install_progressive_mid_report_patch()
install_progressive_full_report_patch()
install_repository_input_normalization()
install_complexity_score_integrity_patch()
install_complexity_score_integrity_compat()
install_complexity_score_integrity_reentry_compat()
install_complexity_density_confidence_patch()
install_complexity_function_measurement_patch()
install_final_score_reconciliation_patch()
install_post_polish_score_reconciliation_patch()

__version__ = "0.1.0"
