from __future__ import annotations

from copy import deepcopy
from typing import Any

VERSION = "nico.comprehensive_internal_capability_matrix.v1"
BASELINE_COMMIT = "d30e60e7033465c8edc19f6a6420a3717a305be7"
REFERENCE_RUN_ID = "comprun_0ea5407d6ffd474c865181a0c00c2ef2"

_REQUIRED_FIELDS = (
    "capability_id",
    "source_paths",
    "entry_points",
    "required_inputs",
    "produced_artifacts",
    "dependencies",
    "persistent_data",
    "validators",
    "tests",
    "production_proofs",
    "client_outputs",
    "current_status",
    "known_failures",
    "external_evidence_dependencies",
)


def _item(
    capability_id: str,
    *,
    source_paths: tuple[str, ...],
    entry_points: tuple[str, ...],
    required_inputs: tuple[str, ...],
    produced_artifacts: tuple[str, ...],
    dependencies: tuple[str, ...],
    persistent_data: tuple[str, ...],
    validators: tuple[str, ...],
    tests: tuple[str, ...],
    production_proofs: tuple[str, ...],
    client_outputs: tuple[str, ...],
    current_status: str = "mechanically_implemented_unqualified",
    known_failures: tuple[str, ...] = (),
    external_evidence_dependencies: tuple[str, ...] = (),
) -> dict[str, Any]:
    return {
        "capability_id": capability_id,
        "source_paths": list(source_paths),
        "entry_points": list(entry_points),
        "required_inputs": list(required_inputs),
        "produced_artifacts": list(produced_artifacts),
        "dependencies": list(dependencies),
        "persistent_data": list(persistent_data),
        "validators": list(validators),
        "tests": list(tests),
        "production_proofs": list(production_proofs),
        "client_outputs": list(client_outputs),
        "current_status": current_status,
        "known_failures": list(known_failures),
        "external_evidence_dependencies": list(external_evidence_dependencies),
    }


_COMMON_PROVIDER_PATHS = (
    "nico/comprehensive_capability_registry.py",
    "nico/comprehensive_production_capabilities.py",
    "nico/comprehensive_native_providers.py",
    "nico/comprehensive_native_providers_v4.py",
    "nico/comprehensive_native_providers_v5.py",
)
_COMMON_STAGE_TESTS = (
    "tests/test_comprehensive_orchestration_contract.py",
    "tests/test_comprehensive_production_bootstrap.py",
)
_COMMON_PROOFS = (
    ".github/workflows/phase9-comprehensive-production-proof.yml",
    ".github/workflows/two-service-production-acceptance.yml",
)
_REPORT_PATHS = (
    "nico/comprehensive_report_package.py",
    "nico/comprehensive_decision_grade_report_v5.py",
    "nico/comprehensive_report_truth_v53.py",
    "nico/comprehensive_final_artifact_truth_v53.py",
)
_REPORT_TESTS = (
    "tests/test_comprehensive_final_artifact_truth_v54.py",
    "tests/test_cross_format_production_truth_v2.py",
)
_REPORT_PROOFS = (
    ".github/workflows/phase9-client-delivery-proof.yml",
    ".github/workflows/phase9-production-report-and-node-scanners.yml",
    ".github/workflows/phase9-comprehensive-production-proof.yml",
)


CAPABILITIES: tuple[dict[str, Any], ...] = (
    _item(
        "authorization_scope",
        source_paths=("nico/comprehensive_production_capabilities.py", "nico/comprehensive_run_service.py"),
        entry_points=("_authorization_provider", "ComprehensiveRunService.start"),
        required_inputs=("service_id", "repository", "commit_sha", "authorization"),
        produced_artifacts=("authorization_and_scope stage",),
        dependencies=("authenticated request",),
        persistent_data=("comprehensive run record",),
        validators=("validate_comprehensive_run_record",),
        tests=_COMMON_STAGE_TESTS,
        production_proofs=_COMMON_PROOFS,
        client_outputs=("Authorization and Scope",),
        current_status="operational",
    ),
    _item(
        "immutable_repository_snapshot",
        source_paths=("nico/repository_snapshot.py", "nico/comprehensive_native_providers.py"),
        entry_points=("capture_repository_snapshot", "snapshot_provider"),
        required_inputs=("authorized repository", "expected commit SHA"),
        produced_artifacts=("immutable snapshot", "tree SHA"),
        dependencies=("GitHub repository access",),
        persistent_data=("snapshot record",),
        validators=("snapshot_provider exact commit check",),
        tests=("tests/test_repository_snapshot_public_git_fallback.py", *_COMMON_STAGE_TESTS),
        production_proofs=_COMMON_PROOFS,
        client_outputs=("Immutable commit identity",),
        current_status="operational",
    ),
    _item(
        "architecture_data_flow_analysis",
        source_paths=(*_COMMON_PROVIDER_PATHS, "nico/snapshot_repository_evidence.py"),
        entry_points=("architecture_data_flow_provider", "collect_snapshot_repository_evidence"),
        required_inputs=("immutable snapshot", "repository evidence"),
        produced_artifacts=("architecture_and_data_flow stage",),
        dependencies=("snapshot repository evidence",),
        persistent_data=("stage result",),
        validators=("comprehensive stage adapter",),
        tests=_COMMON_STAGE_TESTS,
        production_proofs=_COMMON_PROOFS,
        client_outputs=("Architecture and Data Flow",),
    ),
    _item(
        "developer_delivery_process_evidence",
        source_paths=(*_COMMON_PROVIDER_PATHS, "nico/snapshot_repository_evidence.py"),
        entry_points=("delivery_process_provider",),
        required_inputs=("repository activity evidence", "workflow evidence"),
        produced_artifacts=("developer_delivery_process stage",),
        dependencies=("bounded GitHub history",),
        persistent_data=("stage result",),
        validators=("comprehensive stage adapter",),
        tests=_COMMON_STAGE_TESTS,
        production_proofs=_COMMON_PROOFS,
        client_outputs=("Developer Delivery Process",),
    ),
    _item(
        "dependency_scanning",
        source_paths=("nico/snapshot_scanner_worker.py", "nico/scanner_worker.py", "nico/comprehensive_native_providers_v4.py"),
        entry_points=("start_snapshot_scan", "scanner_suite_provider"),
        required_inputs=("immutable snapshot", "pinned dependency scanner configuration"),
        produced_artifacts=("pip-audit artifact", "npm-audit artifact", "osv-scanner artifact"),
        dependencies=("pip-audit", "npm-audit", "osv-scanner"),
        persistent_data=("scan record", "scanner artifacts"),
        validators=("snapshot match", "structured scanner execution normalization"),
        tests=("tests/test_snapshot_scanner_worker.py", "tests/test_dependency_materiality.py"),
        production_proofs=(".github/workflows/frozen-sha-scanner-proof.yml", *_COMMON_PROOFS),
        client_outputs=("Dependency / Library Ecosystem", "candidate register"),
    ),
    _item(
        "secret_scanning",
        source_paths=("nico/snapshot_scanner_worker.py", "nico/scanner_history_truth.py", "nico/comprehensive_native_providers_v4.py"),
        entry_points=("start_snapshot_scan", "scanner_suite_provider"),
        required_inputs=("immutable snapshot", "history-aware scanner configuration"),
        produced_artifacts=("gitleaks artifact", "trufflehog artifact"),
        dependencies=("gitleaks", "trufflehog"),
        persistent_data=("scan record", "scanner artifacts"),
        validators=("snapshot match", "secret category isolation"),
        tests=("tests/test_scanner_redaction_safety.py", "tests/test_security_scanner_remediation.py"),
        production_proofs=(".github/workflows/frozen-sha-scanner-proof.yml", *_COMMON_PROOFS),
        client_outputs=("Secrets Exposure Review", "candidate register"),
    ),
    _item(
        "static_analysis",
        source_paths=("nico/snapshot_scanner_worker.py", "nico/comprehensive_native_providers_v4.py", "nico/comprehensive_native_providers_v5.py"),
        entry_points=("start_snapshot_scan", "scanner_suite_provider"),
        required_inputs=("immutable snapshot", "pinned static analyzer configuration"),
        produced_artifacts=("bandit artifact", "semgrep artifact", "eslint artifact", "typescript artifact"),
        dependencies=("bandit", "semgrep", "eslint", "typescript"),
        persistent_data=("scan record", "scanner artifacts"),
        validators=("snapshot match", "structured scanner execution normalization"),
        tests=("tests/test_scanner_artifact_scoring.py", "tests/test_scanner_applicability_v2.py"),
        production_proofs=(".github/workflows/frozen-sha-scanner-proof.yml", *_COMMON_PROOFS),
        client_outputs=("Static Analysis", "candidate register"),
    ),
    _item(
        "candidate_normalization_clustering",
        source_paths=("nico/comprehensive_native_providers_v5.py", "nico/client_readiness_candidate_triage.py"),
        entry_points=("build_canonical_scanner_finding_register", "build_candidate_triage_package"),
        required_inputs=("retained scanner records", "exact commit SHA"),
        produced_artifacts=("stable candidate IDs", "candidate clusters"),
        dependencies=("scanner artifacts",),
        persistent_data=("candidate register", "cluster digest"),
        validators=("validate_candidate_triage_package",),
        tests=("tests/test_client_readiness_candidate_triage.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Review-Required Candidate Register",),
    ),
    _item(
        "candidate_review_disposition",
        source_paths=("nico/client_readiness_candidate_triage.py",),
        entry_points=("apply_candidate_decisions", "validate_candidate_triage_package"),
        required_inputs=("authorized human decisions", "candidate digest"),
        produced_artifacts=("candidate decision register",),
        dependencies=("candidate normalization and clustering",),
        persistent_data=("review decision records",),
        validators=("stale digest", "duplicate coverage", "bulk decision authorization"),
        tests=("tests/test_client_readiness_candidate_triage.py",),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("candidate dispositions",),
        current_status="mechanically_implemented_unqualified",
        external_evidence_dependencies=("authorized reviewer decisions",),
    ),
    _item(
        "evidence_reconciliation",
        source_paths=("nico/comprehensive_report_truth_v53.py", "nico/comprehensive_final_artifact_truth_v53.py"),
        entry_points=("prepare_report_stage_results", "stabilize_report_package"),
        required_inputs=("completed stage results", "canonical scanner truth"),
        produced_artifacts=("reconciled evidence tree",),
        dependencies=("all automated stages",),
        persistent_data=("canonical report JSON",),
        validators=("final artifact truth", "scanner count parity"),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Evidence Reconciliation and Scoring",),
        current_status="operational_with_known_integration_failure",
        known_failures=("live final publication omits deployment arithmetic remainder",),
    ),
    _item(
        "technical_scoring",
        source_paths=("nico/comprehensive_native_providers.py", "nico/comprehensive_native_providers_v4.py", "nico/comprehensive_report_truth_v53.py"),
        entry_points=("canonical_scoring_provider", "_attach_score_reconciliation"),
        required_inputs=("repository evidence", "scanner evidence", "complexity evidence"),
        produced_artifacts=("technical score", "score reconciliation manifest"),
        dependencies=("evidence reconciliation",),
        persistent_data=("scoring stage assessment",),
        validators=("score truth scope", "cross-format score parity"),
        tests=("tests/test_comprehensive_score_truth_scope_v4.py", *_REPORT_TESTS),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Technical Maturity", "Canonical Technical Scorecard"),
    ),
    _item(
        "evidence_adjusted_scoring",
        source_paths=("nico/comprehensive_native_providers_v4.py", "nico/comprehensive_report_truth_v53.py"),
        entry_points=("canonical_scoring_provider", "_attach_score_reconciliation"),
        required_inputs=("technical score", "assurance deductions", "candidate workload"),
        produced_artifacts=("evidence-adjusted score", "formula inputs"),
        dependencies=("technical scoring", "candidate disposition summary"),
        persistent_data=("scoring stage assessment",),
        validators=("canonical evidence-adjusted score parity",),
        tests=("tests/test_comprehensive_score_truth_scope_v4.py", *_REPORT_TESTS),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Evidence-Adjusted",),
    ),
    _item(
        "ci_cd_configuration_analysis",
        source_paths=(*_COMMON_PROVIDER_PATHS, "nico/snapshot_repository_evidence.py"),
        entry_points=("technical_analysis_provider",),
        required_inputs=("exact-SHA workflow files",),
        produced_artifacts=("immutable CI/CD configuration evidence",),
        dependencies=("repository snapshot",),
        persistent_data=("technical analysis stage",),
        validators=("workflow configuration exact-SHA match",),
        tests=("tests/test_comprehensive_live_state_truth.py", *_COMMON_STAGE_TESTS),
        production_proofs=_COMMON_PROOFS,
        client_outputs=("CI/CD Analysis",),
    ),
    _item(
        "operational_workflow_deployment_analysis",
        source_paths=("nico/comprehensive_human_review_package_cleanup_v1.py", "nico/client_readiness_operational_proof.py", "nico/snapshot_repository_evidence.py"),
        entry_points=("build_ci_operational_stage", "build_operational_proof_bundle"),
        required_inputs=("workflow outcomes", "job outcomes", "deployment outcomes"),
        produced_artifacts=("ci_operational_context", "operational proof bundle"),
        dependencies=("bounded GitHub operational evidence",),
        persistent_data=("stage evidence", "operational proof manifest"),
        validators=("deployment population reconciliation", "operational proof validator"),
        tests=("tests/test_comprehensive_human_review_package_cleanup_v1.py", "tests/test_client_readiness_operational_proof.py"),
        production_proofs=(".github/workflows/two-service-production-acceptance.yml", ".github/workflows/ios-webkit-paint-proof.yml", ".github/workflows/mobile-restart-production-proof.yml"),
        client_outputs=("CI/CD Operational Readiness and Historical Health",),
        current_status="blocked_by_known_code_defect",
        known_failures=("10 observed and 7 successful can be rendered without the required remainder in the live final report path",),
    ),
    _item(
        "complexity_analysis",
        source_paths=("nico/full_assessment_complexity_evidence.py", "nico/snapshot_repository_evidence.py", "nico/comprehensive_native_providers.py"),
        entry_points=("collect_complexity_evidence", "technical_analysis_provider"),
        required_inputs=("exact-SHA first-party source archive",),
        produced_artifacts=("complexity metrics", "hotspot records"),
        dependencies=("repository snapshot",),
        persistent_data=("complexity evidence",),
        validators=("exact source scope",),
        tests=("tests/test_full_assessment_complexity_evidence.py",),
        production_proofs=_COMMON_PROOFS,
        client_outputs=("Architecture & Technical Debt", "Velocity / Complexity"),
    ),
    _item(
        "exact_source_finding_generation",
        source_paths=("nico/comprehensive_native_providers_v5.py", "nico/full_assessment_complexity_evidence.py"),
        entry_points=("build_canonical_scanner_finding_register", "collect_complexity_evidence"),
        required_inputs=("complexity evidence", "exact source locations"),
        produced_artifacts=("stable exact-source finding register",),
        dependencies=("complexity analysis",),
        persistent_data=("findings register",),
        validators=("exact-source index validation",),
        tests=("tests/test_comprehensive_exact_source_index_validation_v1.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Compact Finding and Remediation Register", "Complete Exact-Source Index"),
    ),
    _item(
        "finding_review_disposition",
        source_paths=("nico/client_readiness_finding_disposition.py",),
        entry_points=("build_finding_disposition_package", "validate_finding_disposition_package"),
        required_inputs=("exact finding digest", "authorized decisions"),
        produced_artifacts=("finding disposition register",),
        dependencies=("exact-source finding register",),
        persistent_data=("finding decision records",),
        validators=("stale identity", "owner", "verification", "residual-risk authority"),
        tests=("tests/test_client_readiness_finding_disposition.py",),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("finding dispositions",),
        external_evidence_dependencies=("authorized reviewer decisions",),
    ),
    _item(
        "functional_qa_evidence_intake",
        source_paths=("nico/client_readiness_evidence_intake.py", "nico/comprehensive_native_providers.py"),
        entry_points=("build_client_evidence_package", "functional_qa_provider"),
        required_inputs=("repository test evidence", "optional client runtime evidence"),
        produced_artifacts=("Functional QA review section",),
        dependencies=("client evidence intake contract",),
        persistent_data=("human evidence module",),
        validators=("validate_client_evidence_package",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Functional QA",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("approved runtime journey evidence",),
    ),
    _item(
        "platform_parity_evidence_intake",
        source_paths=("nico/client_readiness_evidence_intake.py", "nico/comprehensive_native_providers.py"),
        entry_points=("build_client_evidence_package", "platform_parity_provider"),
        required_inputs=("repository platform indicators", "optional device evidence"),
        produced_artifacts=("Platform Parity review section",),
        dependencies=("client evidence intake contract",),
        persistent_data=("human evidence module",),
        validators=("validate_client_evidence_package",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=(".github/workflows/ios-webkit-paint-proof.yml", *_REPORT_PROOFS),
        client_outputs=("Platform Parity",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("approved device and parity evidence",),
    ),
    _item(
        "historical_trend_evidence",
        source_paths=("nico/client_readiness_evidence_intake.py", "nico/comprehensive_native_providers.py"),
        entry_points=("historical_trends_provider",),
        required_inputs=("bounded workflow history", "optional incident evidence"),
        produced_artifacts=("Historical Trends review section",),
        dependencies=("repository activity evidence",),
        persistent_data=("stage result", "human evidence module"),
        validators=("outcome taxonomy", "client evidence validation"),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Historical Trends and Change Failure",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("incident, rollback, and recovery records",),
    ),
    _item(
        "requirements_traceability",
        source_paths=("nico/client_readiness_evidence_intake.py", "nico/comprehensive_native_providers.py"),
        entry_points=("requirements_traceability_provider",),
        required_inputs=("repository indicators", "optional authoritative requirements"),
        produced_artifacts=("Requirements Traceability review section",),
        dependencies=("client evidence intake contract",),
        persistent_data=("human evidence module",),
        validators=("validate_client_evidence_package",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Requirements Traceability",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("approved specifications and acceptance criteria",),
    ),
    _item(
        "stakeholder_alignment_evidence",
        source_paths=("nico/client_readiness_evidence_intake.py", "nico/strategic_human_evidence_binding_v1.py"),
        entry_points=("build_client_evidence_package", "install_strategic_human_evidence_binding"),
        required_inputs=("optional authorized stakeholder evidence",),
        produced_artifacts=("Stakeholder Alignment review section",),
        dependencies=("human context boundary",),
        persistent_data=("human evidence module",),
        validators=("identity and provenance binding",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Stakeholder and Business Alignment",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("business, technical, budget, and residual-risk authorities",),
    ),
    _item(
        "risk_briefing",
        source_paths=("nico/comprehensive_native_providers.py", "nico/client_readiness_finding_disposition.py"),
        entry_points=("executive_briefing_provider",),
        required_inputs=("canonical findings", "candidate summary"),
        produced_artifacts=("executive risk briefing",),
        dependencies=("finding generation",),
        persistent_data=("stage result",),
        validators=("finding identity parity",),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Risk Reduction and Executive Briefing",),
    ),
    _item(
        "six_month_roadmap_framework",
        source_paths=("nico/comprehensive_native_providers.py", "nico/client_readiness_evidence_intake.py"),
        entry_points=("roadmap_provider",),
        required_inputs=("canonical technical priorities", "optional stakeholder commitments"),
        produced_artifacts=("roadmap framework",),
        dependencies=("risk briefing",),
        persistent_data=("stage result",),
        validators=("client evidence validation",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Six-Month Roadmap",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("approved dates, owners, dependencies, capacity, and budget",),
    ),
    _item(
        "staffing_cost_framework",
        source_paths=("nico/comprehensive_native_providers.py", "nico/client_readiness_evidence_intake.py"),
        entry_points=("resourcing_provider",),
        required_inputs=("technical roadmap", "optional commercial inputs"),
        produced_artifacts=("staffing and cost framework",),
        dependencies=("roadmap framework",),
        persistent_data=("stage result",),
        validators=("client evidence validation",),
        tests=("tests/test_client_readiness_evidence_intake.py",),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Staffing, Sequencing, and Cost",),
        current_status="external_evidence_limited",
        external_evidence_dependencies=("scope, rates, capacity, delivery model, and budget authority",),
    ),
    _item(
        "canonical_json",
        source_paths=_REPORT_PATHS,
        entry_points=("build_comprehensive_report_package",),
        required_inputs=("reconciled stage results",),
        produced_artifacts=("canonical JSON",),
        dependencies=("evidence reconciliation",),
        persistent_data=("report package",),
        validators=("final artifact truth", "canonical digest"),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("structured canonical artifact",),
        current_status="operational_with_known_integration_failure",
        known_failures=("live report path can retain unreconciled deployment evidence before rendering",),
    ),
    _item(
        "pdf_report",
        source_paths=(*_REPORT_PATHS, "nico/comprehensive_human_review_package_cleanup_v1.py"),
        entry_points=("build_comprehensive_report_package", "render_manifest_approval_supplement"),
        required_inputs=("canonical report JSON",),
        produced_artifacts=("PDF",),
        dependencies=("report renderer",),
        persistent_data=("report package",),
        validators=("PDF parseability", "full PDF text validation", "artifact parity"),
        tests=_REPORT_TESTS,
        production_proofs=(".github/workflows/ios-webkit-paint-proof.yml", ".github/workflows/mobile-restart-production-proof.yml", *_REPORT_PROOFS),
        client_outputs=("36-page review package",),
        current_status="blocked_by_known_code_defect",
        known_failures=("live final report publication rejects missing arithmetic deployment remainder",),
    ),
    _item(
        "html_report",
        source_paths=_REPORT_PATHS,
        entry_points=("build_comprehensive_report_package",),
        required_inputs=("canonical report JSON",),
        produced_artifacts=("HTML",),
        dependencies=("report renderer",),
        persistent_data=("report package",),
        validators=("cross-format parity",),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("HTML report",),
        current_status="operational_with_known_integration_failure",
        known_failures=("shares the live deployment reconciliation failure boundary",),
    ),
    _item(
        "markdown_report",
        source_paths=_REPORT_PATHS,
        entry_points=("build_comprehensive_report_package",),
        required_inputs=("canonical report JSON",),
        produced_artifacts=("Markdown",),
        dependencies=("report renderer",),
        persistent_data=("report package",),
        validators=("cross-format parity",),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("Markdown report",),
        current_status="operational_with_known_integration_failure",
        known_failures=("shares the live deployment reconciliation failure boundary",),
    ),
    _item(
        "findings_csv",
        source_paths=("nico/comprehensive_decision_grade_report_v5.py", "nico/client_report_completion_v2.py"),
        entry_points=("build_comprehensive_report_package",),
        required_inputs=("canonical exact-source finding register",),
        produced_artifacts=("findings CSV",),
        dependencies=("finding generation",),
        persistent_data=("report package",),
        validators=("finding count and identity parity",),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("findings export",),
    ),
    _item(
        "evidence_csv",
        source_paths=("nico/comprehensive_decision_grade_report_v5.py", "nico/client_report_completion_v2.py"),
        entry_points=("build_comprehensive_report_package",),
        required_inputs=("canonical evidence rows",),
        produced_artifacts=("evidence CSV",),
        dependencies=("canonical JSON",),
        persistent_data=("report package",),
        validators=("artifact manifest parity",),
        tests=_REPORT_TESTS,
        production_proofs=_REPORT_PROOFS,
        client_outputs=("evidence export",),
    ),
    _item(
        "candidate_register_json",
        source_paths=("nico/client_readiness_candidate_triage.py", "nico/client_report_completion_v2.py"),
        entry_points=("build_candidate_triage_package",),
        required_inputs=("canonical candidate register",),
        produced_artifacts=("candidate-register JSON",),
        dependencies=("candidate normalization",),
        persistent_data=("report package",),
        validators=("candidate digest and count parity",),
        tests=("tests/test_client_readiness_candidate_triage.py", *_REPORT_TESTS),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("candidate register export",),
    ),
    _item(
        "remediation_backlog_json",
        source_paths=("nico/client_readiness_finding_disposition.py", "nico/client_report_completion_v2.py"),
        entry_points=("build_finding_disposition_package",),
        required_inputs=("canonical findings",),
        produced_artifacts=("remediation-backlog JSON",),
        dependencies=("finding generation",),
        persistent_data=("report package",),
        validators=("finding identity parity",),
        tests=("tests/test_client_readiness_finding_disposition.py", *_REPORT_TESTS),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("remediation backlog export",),
    ),
    _item(
        "detached_evidence_manifest",
        source_paths=("nico/client_readiness_exact_artifact_approval.py", "nico/client_readiness_exact_artifact_approval_v2.py"),
        entry_points=("build_exact_artifact_approval_subject",),
        required_inputs=("final artifact bytes", "canonical subject digest"),
        produced_artifacts=("detached evidence manifest",),
        dependencies=("all report artifacts",),
        persistent_data=("approval subject",),
        validators=("exact artifact hash validation",),
        tests=("tests/test_client_readiness_exact_artifact_approval.py",),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("Client Artifact Manifest",),
    ),
    _item(
        "browser_mobile_operation",
        source_paths=("apps/web/app/assessment/page.tsx", "scripts/mobile_restart_live_acceptance.py", "scripts/ios_webkit_live_acceptance.py"),
        entry_points=("Comprehensive assessment UI", "mobile live acceptance scripts"),
        required_inputs=("production frontend", "production API", "exact release SHA"),
        produced_artifacts=("browser screenshots", "mobile proof JSON"),
        dependencies=("frontend and backend deployments",),
        persistent_data=("run ID in URL and durable backend store",),
        validators=("release identity", "review PDF download", "failure layout"),
        tests=("tests/test_two_service_current_ui_acceptance_v13.py", "tests/test_cross_tier_mobile_accessibility_gate.py"),
        production_proofs=(".github/workflows/ios-webkit-paint-proof.yml", ".github/workflows/mobile-restart-production-proof.yml"),
        client_outputs=("mobile assessment and report download",),
        current_status="blocked_by_known_downstream_report_failure",
        known_failures=("browser path reaches final report generation and is blocked by deployment remainder validation",),
    ),
    _item(
        "restart_recovery",
        source_paths=("nico/comprehensive_mobile_recovery_v1.py", "nico/assessment_recovery_execution_patch.py", "nico/comprehensive_run_store.py"),
        entry_points=("continue comprehensive run", "recover exact run"),
        required_inputs=("durable run record", "run ID"),
        produced_artifacts=("recovery proof",),
        dependencies=("Postgres durability",),
        persistent_data=("comprehensive run record",),
        validators=("revision and idempotency", "container replacement durability"),
        tests=("tests/test_assessment_recovery_production_routes.py", "tests/test_postgres_comprehensive_restart.py"),
        production_proofs=(".github/workflows/postgres-restart-proof.yml", ".github/workflows/mobile-restart-production-proof.yml"),
        client_outputs=("same-run recovery",),
        current_status="operational_until_known_downstream_report_failure",
        known_failures=("recovery succeeds through scanning but terminal report publication is blocked",),
    ),
    _item(
        "report_regeneration",
        source_paths=("nico/client_report_completion_v2.py", "nico/comprehensive_run_service.py"),
        entry_points=("prepare_client_report_package", "ComprehensiveRunService"),
        required_inputs=("retained canonical evidence",),
        produced_artifacts=("new report artifact digest",),
        dependencies=("durable run evidence",),
        persistent_data=("report package", "artifact manifest"),
        validators=("same evidence identity", "new digest on changed artifact"),
        tests=("tests/test_comprehensive_review_decision_v1.py", *_REPORT_TESTS),
        production_proofs=_REPORT_PROOFS,
        client_outputs=("regenerated automated review package",),
        current_status="mechanically_implemented_unqualified",
    ),
    _item(
        "human_review_workflow",
        source_paths=("nico/comprehensive_review_decision_v1.py", "nico/comprehensive_run_service.py", "nico/client_readiness_evidence_intake.py"),
        entry_points=("build_reviewed_edition", "ComprehensiveRunService.review"),
        required_inputs=("authorized reviewer", "exact report subject", "decision"),
        produced_artifacts=("review history", "accepted edition record"),
        dependencies=("exact artifact subject",),
        persistent_data=("comprehensive run record",),
        validators=("run record integrity", "review authority"),
        tests=("tests/test_comprehensive_review_decision_v1.py",),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("Human Review and Acceptance Gate",),
        current_status="mechanically_implemented_unqualified",
        external_evidence_dependencies=("authorized human decision",),
    ),
    _item(
        "exact_artifact_approval",
        source_paths=("nico/client_readiness_exact_artifact_approval.py", "nico/client_readiness_exact_artifact_approval_v2.py", "nico/comprehensive_review_decision_v1.py"),
        entry_points=("build_exact_artifact_approval_subject", "build_reviewed_edition"),
        required_inputs=("exact artifact hashes", "reviewer authority", "residual-risk acceptance"),
        produced_artifacts=("approval receipt", "approval subject digest"),
        dependencies=("human review workflow", "detached evidence manifest"),
        persistent_data=("accepted edition",),
        validators=("stale artifact", "changed artifact", "review authority"),
        tests=("tests/test_client_readiness_exact_artifact_approval.py", "tests/test_comprehensive_review_decision_v1.py"),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("Human Review and Exact-Artifact Approval Record",),
        current_status="mechanically_implemented_unqualified",
        external_evidence_dependencies=("authorized human approval",),
    ),
    _item(
        "approved_delivery_packaging",
        source_paths=("nico/client_readiness_approved_delivery.py", "nico/comprehensive_approved_delivery_v1.py", "nico/comprehensive_run_service.py"),
        entry_points=("build_approved_delivery_package", "attach_approved_delivery_package"),
        required_inputs=("valid accepted edition", "approved exact artifact subject"),
        produced_artifacts=("approved delivery ZIP", "delivery authorization certificate"),
        dependencies=("exact-artifact approval",),
        persistent_data=("approved delivery package",),
        validators=("validate_approved_delivery_package",),
        tests=("tests/test_client_readiness_exact_artifact_approval.py", "tests/test_comprehensive_review_decision_v1.py"),
        production_proofs=(".github/workflows/phase9-client-delivery-proof.yml",),
        client_outputs=("Approved Final delivery package",),
        current_status="mechanically_implemented_unqualified",
        external_evidence_dependencies=("authorized human approval",),
    ),
)


PRODUCTION_FAILURE_ROOT_CAUSE: dict[str, Any] = {
    "baseline_commit": BASELINE_COMMIT,
    "affected_workflows": {
        "Unified Production Acceptance": "31036776934",
        "iOS WebKit Paint Proof": "31036777095",
        "Mobile Restart Production Proof": "31036777735",
    },
    "affected_run_ids": (
        "comprun_2a332709a43f484580d9e961f4592b2f",
        "comprun_1215e435d09a45f1ad28aead1ea0089a",
        "comprun_114fe9ac91954833b7333a0e14bcb1a9",
    ),
    "terminal_stage": "final_comprehensive_report_generation",
    "shared_reason": (
        "v2_production_publication_failed:ValueError:"
        "client report omitted the arithmetic deployment remainder"
    ),
    "validated_working_boundaries": (
        "exact frontend deployment identity",
        "exact backend deployment status",
        "Postgres durability and container replacement safety",
        "authorization through risk briefing stage completion",
        "technical score production at 93/100",
    ),
    "defect_classification": "path_divergence_and_evidence_contract_defect",
    "root_mechanism": (
        "The source CI operational stage builder can emit a deployment population with "
        "observed and successful counts plus an incomplete numeric or unavailable class. "
        "Late monkeypatch-based reconciliation passes in isolated tests, but the live "
        "decision-grade report path retains a callable imported by value before that "
        "patch is installed. The final full-artifact validator then correctly rejects "
        "the rendered surface because the arithmetic remainder is absent."
    ),
    "authoritative_repair_boundary": (
        "reconcile deployment population inside the canonical operational evidence "
        "producer before any report builder or renderer consumes it"
    ),
    "prohibited_repair": "another late PDF, HTML, or Markdown text substitution",
}


def capability_matrix() -> list[dict[str, Any]]:
    return deepcopy(list(CAPABILITIES))


def validate_capability_matrix(matrix: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    candidate = matrix if matrix is not None else capability_matrix()
    ids = [str(item.get("capability_id") or "") for item in candidate]
    missing_fields = {
        capability_id: [field for field in _REQUIRED_FIELDS if field not in item]
        for capability_id, item in zip(ids, candidate, strict=False)
        if isinstance(item, dict)
        and any(field not in item for field in _REQUIRED_FIELDS)
    }
    invalid_items = [index for index, item in enumerate(candidate) if not isinstance(item, dict)]
    empty_ids = [index for index, capability_id in enumerate(ids) if not capability_id]
    duplicate_ids = sorted({capability_id for capability_id in ids if ids.count(capability_id) > 1})
    expected_ids = 40
    errors: list[str] = []
    if len(candidate) != expected_ids:
        errors.append(f"capability_count:{len(candidate)}!=40")
    if invalid_items:
        errors.append("non_mapping_items")
    if empty_ids:
        errors.append("empty_capability_ids")
    if duplicate_ids:
        errors.append("duplicate_capability_ids")
    if missing_fields:
        errors.append("missing_required_fields")
    if PRODUCTION_FAILURE_ROOT_CAUSE["terminal_stage"] != "final_comprehensive_report_generation":
        errors.append("production_failure_terminal_stage_drift")
    if "arithmetic deployment remainder" not in PRODUCTION_FAILURE_ROOT_CAUSE["shared_reason"]:
        errors.append("production_failure_reason_drift")
    return {
        "artifact_schema": VERSION,
        "status": "valid" if not errors else "invalid",
        "capability_count": len(candidate),
        "expected_capability_count": expected_ids,
        "capability_ids": ids,
        "duplicate_ids": duplicate_ids,
        "missing_fields": missing_fields,
        "invalid_item_indexes": invalid_items,
        "empty_id_indexes": empty_ids,
        "validation_errors": errors,
        "baseline_commit": BASELINE_COMMIT,
        "reference_run_id": REFERENCE_RUN_ID,
        "known_production_failure": deepcopy(PRODUCTION_FAILURE_ROOT_CAUSE),
        "human_review_required": True,
        "client_delivery_allowed": False,
    }


__all__ = [
    "BASELINE_COMMIT",
    "CAPABILITIES",
    "PRODUCTION_FAILURE_ROOT_CAUSE",
    "REFERENCE_RUN_ID",
    "VERSION",
    "capability_matrix",
    "validate_capability_matrix",
]
