from __future__ import annotations

from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from nico.full_assessment_continuation import apply_full_assessment_continuation, plan_full_assessment_continuation
from nico.full_assessment_orchestrator import run_full_assessment_orchestration
from nico.mid_assessment_handlers import mid_assessment_handlers
from nico.mid_assessment_runs import (
    build_mid_status_payload,
    explicit_model_fields,
    persist_mid_assessment_run,
    persistence_metadata,
)
from nico.storage import STORE, new_id

MID_ASSESSMENT_TYPE = "mid"
MID_REPORT_STATUS = "mid_report_pipeline_pending"


class MidAssessmentRunRequest(BaseModel):
    repository: str = ""
    target: str = ""
    customer_id: str = "default_customer"
    project_id: str = "default_project"
    client_name: str = ""
    project_name: str = ""
    authorized_by: str = "unspecified"
    authorization_scope: str = "repository assessment only"
    authorization_confirmed: bool = False
    authorized: bool = False
    timeframe_days: int = 180
    run_scanners: bool = True
    refresh_full_evidence: bool = True
    auto_continue: bool = True
    tools: list[str] = Field(default_factory=list)


class MidAssessmentStatusRequest(BaseModel):
    repository: str = ""
    target: str = ""
    customer_id: str = "default_customer"
    project_id: str = "default_project"
    client_name: str = ""
    project_name: str = ""
    authorized_by: str = "mid_status_refresh"
    authorization_scope: str = "repository assessment only"
    authorization_confirmed: bool = True
    authorized: bool = True
    timeframe_days: int = 180
    run_scanners: bool = True
    refresh_full_evidence: bool = True
    auto_continue: bool = True
    tools: list[str] = Field(default_factory=list)


def _payload(model: BaseModel) -> dict[str, Any]:
    if hasattr(model, "model_dump"):
        return model.model_dump()  # type: ignore[attr-defined]
    return model.dict()


def _evidence_from_progress(result: dict[str, Any]) -> dict[str, Any]:
    for item in result.get("progress") or []:
        if not isinstance(item, dict) or item.get("step") != "repo_evidence":
            continue
        return item.get("evidence") if isinstance(item.get("evidence"), dict) else {}
    return {}


def _attach_mid_evidence(result: dict[str, Any]) -> dict[str, Any]:
    evidence = _evidence_from_progress(result)
    for response_key, id_key in (
        ("repository_snapshot", "snapshot_id"),
        ("repository_evidence", "repository_evidence_id"),
        ("complexity_evidence", "complexity_evidence_id"),
    ):
        item_id = str(evidence.get(id_key) or "")
        record = STORE.get("evidence_items", item_id) if item_id else None
        value = record.get("evidence") if isinstance(record, dict) and isinstance(record.get("evidence"), dict) else {}
        result[response_key] = value
    return result


def _attach_mid_contract(result: dict[str, Any]) -> dict[str, Any]:
    result["assessment_type"] = MID_ASSESSMENT_TYPE
    result["service_tier"] = MID_ASSESSMENT_TYPE
    result["mode"] = MID_ASSESSMENT_TYPE
    result["unified_run"] = True
    result["express_report_generated"] = False
    result["report_generation_status"] = MID_REPORT_STATUS
    result["report_generation_note"] = (
        "This Mid run executes snapshot-bound collection, scanners, evidence attachment, and evidence-bound scoring in one run. "
        "Mid-specific report and review artifacts are added only by the guarded Mid report pipeline; no Express or Full report is generated by this endpoint stage."
    )
    result["human_review_required"] = True
    result["client_ready"] = False
    assessment = result.get("assessment") if isinstance(result.get("assessment"), dict) else {}
    if assessment:
        assessment["assessment_type"] = MID_ASSESSMENT_TYPE
        assessment["service_tier"] = MID_ASSESSMENT_TYPE
        assessment["human_review_required"] = True
        assessment["client_ready"] = False
        result["assessment"] = assessment
    return result


def _record(result: dict[str, Any], payload: dict[str, Any], *, restored: bool) -> dict[str, Any]:
    metadata = persistence_metadata(restored=restored)
    result["persistence"] = metadata
    try:
        record = persist_mid_assessment_run(result, payload)
    except Exception:
        result["persistence"] = {
            "recorded": False,
            "durable": False,
            "adapter": metadata.get("adapter") or "unknown",
            "restored": restored,
            "note": "Mid-run state could not be recorded and must not be treated as restart-resumable.",
        }
        return result
    result["persistence"].update(
        {
            "record_id": record.get("run_id") or result.get("run_id"),
            "created_at": record.get("created_at"),
            "updated_at": record.get("updated_at"),
        }
    )
    return result


def _blocked_detail(result: dict[str, Any], message: str) -> dict[str, Any]:
    return {
        "status": "blocked",
        "code": str(result.get("error") or "blocked")[:80],
        "message": message,
        "run_id": result.get("run_id") or "",
        "assessment_type": MID_ASSESSMENT_TYPE,
        "progress": result.get("progress") or [],
        "persistence": result.get("persistence") or {},
    }


def mid_assessment_response(req: MidAssessmentRunRequest) -> dict[str, Any]:
    payload = _payload(req)
    payload.update(
        {
            "run_id": new_id("midrun"),
            "mode": MID_ASSESSMENT_TYPE,
            "build_reports": False,
            "create_final_review_request": False,
        }
    )
    handlers = mid_assessment_handlers(int(payload.get("timeframe_days") or 180))
    result = run_full_assessment_orchestration(payload, handlers=handlers)
    result = _attach_mid_evidence(result)
    result = _attach_mid_contract(result)
    result = _record(result, payload, restored=False)
    if result.get("status") == "blocked":
        raise HTTPException(status_code=400, detail=_blocked_detail(result, "Mid Assessment was blocked by authorization or repository validation."))
    return result


def mid_assessment_status_response(run_id: str, req: MidAssessmentStatusRequest) -> dict[str, Any]:
    if not str(run_id or "").startswith("midrun_"):
        raise HTTPException(status_code=404, detail={"status": "not_found", "message": "Mid Assessment run not found."})
    request_payload = _payload(req)
    payload, record = build_mid_status_payload(run_id, request_payload, explicit_model_fields(req))
    if not record:
        raise HTTPException(status_code=404, detail={"status": "not_found", "message": "Mid Assessment run not found."})
    saved_request = dict(record.get("request") or {})
    auto_continue = bool(request_payload.get("auto_continue")) if "auto_continue" in explicit_model_fields(req) else bool(saved_request.get("auto_continue", True))
    plan = plan_full_assessment_continuation(payload, record, auto_continue=auto_continue)
    continuation = plan["payload"]
    continuation["mode"] = MID_ASSESSMENT_TYPE
    continuation["build_reports"] = False
    continuation["create_final_review_request"] = False
    handlers = mid_assessment_handlers(int(continuation.get("timeframe_days") or 180))
    result = run_full_assessment_orchestration(continuation, handlers=handlers)
    result = apply_full_assessment_continuation(result, plan)
    result["status_refresh"] = True
    result = _attach_mid_evidence(result)
    result = _attach_mid_contract(result)
    result = _record(result, continuation, restored=True)
    if result.get("status") == "blocked":
        raise HTTPException(status_code=400, detail=_blocked_detail(result, "Mid Assessment status refresh was blocked."))
    return result


def register_mid_assessment_routes(app: FastAPI) -> None:
    app.post("/assessment/mid-run")(mid_assessment_response)
    app.post("/assessment/mid-run/{run_id}/status")(mid_assessment_status_response)


__all__ = [
    "MID_ASSESSMENT_TYPE",
    "MID_REPORT_STATUS",
    "MidAssessmentRunRequest",
    "MidAssessmentStatusRequest",
    "mid_assessment_response",
    "mid_assessment_status_response",
    "register_mid_assessment_routes",
]
