from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from nico.storage import STORE


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def markdown_report(payload: dict[str, Any]) -> str:
    lines = [
        f"# NICO Client-Ready Report Package",
        "",
        f"Generated: {now_iso()}",
        f"Client: {payload.get('client_name') or 'Not specified'}",
        f"Project: {payload.get('project_name') or 'Not specified'}",
        f"Repository/source scope: {payload.get('repository') or payload.get('source_scope') or 'Not specified'}",
        "",
        "## Authorization Statement",
        payload.get("authorization_statement") or "Assessment output is valid only for explicitly authorized customer/project scope.",
        "",
        "## Human Review Requirement",
        "Final delivery, roadmap commitments, resourcing decisions, and code changes require human review.",
        "",
        "## Maturity Signal",
        json.dumps(payload.get("maturity_signal") or {}, indent=2),
        "",
        "## Evidence Readiness",
        json.dumps(payload.get("evidence_readiness") or {}, indent=2),
        "",
        "## Findings and Risks",
    ]
    for item in payload.get("findings", []) or payload.get("sections", []):
        if isinstance(item, dict):
            lines.append(f"- {item.get('label') or item.get('id')}: {item.get('summary') or item.get('status')}")
        else:
            lines.append(f"- {item}")
    lines += ["", "## Unavailable Data Notes"]
    for note in payload.get("unavailable_data_notes", []) or []:
        lines.append(f"- {note}")
    lines += ["", "## Next Steps"]
    for step in payload.get("next_steps", []) or ["Review evidence.", "Prioritize repair plan.", "Approve or reject any production-impacting action."]:
        lines.append(f"- {step}")
    return "\n".join(lines).strip() + "\n"


def html_report(markdown: str) -> str:
    safe = html.escape(markdown)
    return f"""<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>NICO Report</title><style>body{{font-family:Arial,sans-serif;max-width:980px;margin:40px auto;padding:0 20px;line-height:1.55;color:#111827}}pre{{white-space:pre-wrap;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:24px}}</style></head><body><pre>{safe}</pre></body></html>"""


def build_report_package(payload: dict[str, Any]) -> dict[str, Any]:
    report_id = f"report_{uuid4().hex[:16]}"
    markdown = markdown_report(payload)
    package = {
        "status": "complete",
        "report_id": report_id,
        "customer_id": payload.get("customer_id") or "default_customer",
        "project_id": payload.get("project_id") or "default_project",
        "run_id": payload.get("run_id") or payload.get("assessment_id") or report_id,
        "formats": {
            "markdown": markdown,
            "html": html_report(markdown),
            "json": payload,
            "pdf": None,
        },
        "unavailable_data_notes": ["PDF export is generated by the Express report path or a configured report worker; this package stores Markdown, HTML, and JSON."],
        "created_at": now_iso(),
    }
    STORE.put("reports", report_id, package)
    STORE.audit("report.created", {"report_id": report_id, "run_id": package["run_id"]}, customer_id=package["customer_id"], project_id=package["project_id"])
    return package


def get_report(run_id: str) -> dict[str, Any]:
    for report in STORE.list("reports"):
        if report.get("run_id") == run_id or report.get("report_id") == run_id:
            return report
    return {"status": "not_found", "run_id": run_id}


def export_report(run_id: str, export_format: str = "json") -> dict[str, Any]:
    report = get_report(run_id)
    if report.get("status") == "not_found":
        return report
    formats = report.get("formats", {})
    if export_format not in formats or formats.get(export_format) is None:
        return {"status": "unavailable", "run_id": run_id, "format": export_format, "available_formats": [key for key, value in formats.items() if value is not None]}
    return {"status": "complete", "run_id": run_id, "format": export_format, "content": formats[export_format]}
