from __future__ import annotations

from typing import Any

from nico.setup_readiness import setup_readiness_snapshot

ACTION_METADATA = {
    "backend_url_configured": {
        "owner": "frontend_admin",
        "system": "Vercel",
        "priority": "critical",
        "command": "Set NEXT_PUBLIC_NICO_API_URL to the Railway backend URL and redeploy the frontend.",
    },
    "backend_online": {
        "owner": "backend_admin",
        "system": "Railway",
        "priority": "critical",
        "command": "Open the backend /health endpoint and fix runtime failures until status is ok.",
    },
    "persistence_active": {
        "owner": "backend_admin",
        "system": "Railway Postgres",
        "priority": "critical",
        "command": "Attach Postgres, set DATABASE_URL, redeploy, and confirm /storage/status persistence_available=true.",
    },
    "express_run_id_available": {
        "owner": "operator",
        "system": "NICO Express",
        "priority": "high",
        "command": "Rerun Express and confirm the returned payload includes run_id.",
    },
    "final_review_url_available": {
        "owner": "operator",
        "system": "NICO Final Review",
        "priority": "high",
        "command": "Use the run-scoped final_review.url generated by Express.",
    },
    "final_review_requested": {
        "owner": "human_reviewer",
        "system": "NICO Final Review",
        "priority": "high",
        "command": "Open /final-review and request final review for the exact run/customer/project scope.",
    },
    "final_review_approved": {
        "owner": "human_reviewer",
        "system": "NICO Final Review",
        "priority": "high",
        "command": "Approve final review only after checking evidence, unavailable-data notes, and delivery context.",
    },
    "acceptance_green_after_rerun": {
        "owner": "operator",
        "system": "NICO Express",
        "priority": "high",
        "command": "Rerun Express after final-review approval so Client / Human Acceptance can turn green.",
    },
    "express_completion_present": {
        "owner": "developer",
        "system": "NICO Reporting",
        "priority": "medium",
        "command": "Attach Express Service Completion to the returned Express result before client delivery.",
    },
}

PRIORITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


def setup_action_plan(payload: dict[str, Any]) -> dict[str, Any]:
    readiness = setup_readiness_snapshot(payload)
    check_by_id = {item["id"]: item for item in readiness.get("checks", [])}
    actions = []
    for check_id in readiness.get("remaining", []):
        check = check_by_id.get(check_id, {})
        meta = ACTION_METADATA.get(check_id, {})
        actions.append(
            {
                "id": check_id,
                "label": check.get("label") or check_id.replace("_", " ").title(),
                "priority": meta.get("priority", "medium"),
                "owner": meta.get("owner", "operator"),
                "system": meta.get("system", "NICO"),
                "action": meta.get("command") or check.get("fix") or "Review setup readiness and resolve the missing gate.",
                "why": check.get("fix") or "This gate is required before max-target workflow validation.",
            }
        )
    actions.sort(key=lambda item: (PRIORITY_ORDER.get(item["priority"], 9), item["id"]))
    return {
        "status": readiness.get("status"),
        "readiness_score": readiness.get("score"),
        "ready_for_max_target_validation": readiness.get("score") == 100,
        "next_action": actions[0] if actions else None,
        "actions": actions,
        "readiness": readiness,
        "rule": "Setup actions are ordered by deployment impact. Human review and acceptance must remain explicit manual gates.",
    }
