cmake_minimum_required(VERSION 3.31)
project(NicoOrderedNativeContexts LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES ON)
configure_file(config.h.in generated/config.h @ONLY)
add_subdirectory(alpha)
add_subdirectory(beta)
